swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      tags:
        - Transactions Module
      summary: Get Transactions
      description: API for getting all transactions for the current month, grouped by account.
      parameters:
        - in: query
          name: accountId
          description: Account ID to get transactions for (optional)
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved transactions
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '404':
          description: No transactions found for the specified account

  /transactions/{transactionId}:
    get:
      tags:
        - Transactions Module
      summary: Get Transaction Details
      description: API for getting details of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          description: Transaction ID to get details for
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved transaction details
          schema:
            $ref: '#/definitions/TransactionDetailsResponse'
        '404':
          description: Transaction not found
    post:
      tags:
        - Transactions Module
      summary: Update Transaction
      description: API for updating information on a specific transaction.
      parameters:
        - in: path
          name: transactionId
          description: Transaction ID to update
          required: true
          type: string
        - in: body
          name: body
          description: Transaction update payload
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Successfully updated transaction
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Transaction not found
    delete:
      tags:
        - Transactions Module
      summary: Delete Transaction
      description: API for deleting information on a specific transaction.
      parameters:
        - in: path
          name: transactionId
          description: Transaction ID to delete
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successfully deleted transaction
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Transaction not found
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Transaction:
    type: object
    properties:
      id:
        type: string
      accountId:
        type: string
      amount:
        type: number
      date:
        type: string
      description:
        type: string
  TransactionDetailsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/Transaction'
  TransactionUpdate:
    type: object
    properties:
      amount:
        type: number
      date:
        type: string
      description:
        type: string
